### ISSUE TITLE
Error when trying to install OMEKA 3.1.2 with PHP 8.1.2 

### ISSUE THREAD

**Issue by jmf-nyu** [omeka/Omeka#1011]
Hi,

When I try to install OMEKA on my server, I receive the following error message:

```
Fatal error: Uncaught Error: Call to undefined function mysqli_report() in /var/www/html/omeka/application/libraries/Omeka/Application/Resource/Db.php:63 Stack trace: #0 /var/www/html/omeka/application/libraries/Zend/Application/Bootstrap/BootstrapAbstract.php(685): Omeka_Application_Resource_Db->init() #1 /var/www/html/omeka/application/libraries/Zend/Application/Bootstrap/BootstrapAbstract.php(628): Zend_Application_Bootstrap_BootstrapAbstract->_executeResource() #2 /var/www/html/omeka/application/libraries/Zend/Application/Bootstrap/BootstrapAbstract.php(588): Zend_Application_Bootstrap_BootstrapAbstract->_bootstrap() #3 /var/www/html/omeka/install/install.php(41): Zend_Application_Bootstrap_BootstrapAbstract->bootstrap() #4 {main} thrown in /var/www/html/omeka/application/libraries/Omeka/Application/Resource/Db.php on line 63
```

Running Ubuntu 22.04.3, PHP 8.1.2, MariaDB 15.1.

**Comment by zerocrates** [comment]
Seems like you might not have the mysqli extension installed... if you're setting up this server yourself, make sure you have the php-mysql package installed.

**Comment by jmf-nyu** [comment]
Thank you! That did it.
