### ISSUE TITLE
SQL Incorrect datetime value: '0000-00-00 00:00:00' during migration

### ISSUE THREAD

**Issue by cg923** [omeka/Omeka#846]
While creating a new omeka 2.6 site, I encountered the following error on two different development environments (PHP 5.6, PHP 7.1).

`exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli statement execute error : Incorrect datetime value: '0000-00-00 00:00:00' for column 'added' at row 1' in /home/gselover/private_html/omeka/new_test/application/libraries/Zend/Db/Statement/Mysqli.php:214
Stack trace:
#0 /home/gselover/private_html/omeka/new_test/application/libraries/Zend/Db/Statement.php(303): Zend_Db_Statement_Mysqli->_execute(Array)
#1 /home/gselover/private_html/omeka/new_test/application/libraries/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 [internal function]: Zend_Db_Adapter_Abstract->query('ALTER TABLE `ne...')
#3 /home/gselover/private_html/omeka/new_test/application/libraries/Omeka/Db.php(79): call_user_func_array(Array, Array)
#4 /home/gselover/private_html/omeka/new_test/application/migrations/20170331084000_changeFileSizeBigInt.php(17): Omeka_Db->__call('query', Array)
#5 /home/gselover/private_html/omeka/new_test/application/migrations/20170331084000_changeFileSizeBigInt.php(17): Omeka_Db->query('ALTER TABLE `ne...')
#6 /home/gselover/private_html/omeka/new_test/application/libraries/Omeka/Db/Migration/Manager.php(229): changeFileSizeBigInt->up()
#7 /home/gselover/private_html/omeka/new_test/application/libraries/Omeka/Db/Migration/Manager.php(106): Omeka_Db_Migration_Manager->_migrateUp(Object(DateTime))
#8 /home/gselover/private_html/omeka/new_test/application/controllers/UpgradeController.php(46): Omeka_Db_Migration_Manager->migrate()
#9 /home/gselover/private_html/omeka/new_test/application/libraries/Zend/Controller/Action.php(516): UpgradeController->migrateAction()
#10 /home/gselover/private_html/omeka/new_test/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('migrateAction')
#11 /home/gselover/private_html/omeka/new_test/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#12 /home/gselover/private_html/omeka/new_test/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#13 /home/gselover/private_html/omeka/new_test/application/libraries/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#14 /home/gselover/private_html/omeka/new_test/application/libraries/Omeka/Application.php(73): Zend_Application->run()
#15 /home/gselover/private_html/omeka/new_test/admin/index.php(28): Omeka_Application->run()
#16 {main}`

I was able to resolve the issue by making the following change to application/libraries/Omeka/Db/Migration/Manager.php:
`public function migrate($endTimestamp = null)
    {
        ini_set('max_execution_time', 0);
        //$stop = new DateTime($endTimestamp);
        $stop = new DateTime('0000-00-00 00:00:00');
	$direction = 'up';
        if ($direction == 'up') {
            $this->_migrateUp($stop);
        } else {
            $this->_migrateDown($stop);
        }
    }
 `
I am rather new to Omeka so I'm not sure if this would create any problems, but it seems to work.  Is this an issue that others have experienced?  Or is it likely a result of changes we may have made to our codebase?

**Comment by zerocrates** [comment]
If you're creating a new Omeka site you wouldn't have any migrations happening at all... were you upgrading instead?

**Comment by cg923** [comment]
Ah, yes.  I'll edit my comment.
