### ISSUE TITLE
Error when setting up storage in S3

### ISSUE THREAD

**Issue by MagnusEnger** [omeka/Omeka#866]
Thanks for your hard work on Omeka - truly a great tool! 

I am trying to set up Classic with storage in Amazon S3, following the description at https://bavatuesdays.com/setting-up-s3-storage-for-omeka/. 

I have the following config in application/config/config.ini:

```
storage.adapter = "Omeka_Storage_Adapter_ZendS3"
storage.adapterOptions.accessKeyId = x
storage.adapterOptions.secretAccessKey = y
storage.adapterOptions.bucket = z.example.com
storage.adapterOptions.expiration = 1 ; URL expiration time (in minutes)
storage.adapterOptions.endpoint = https://s3-eu-west-1.amazonaws.com ; Custom S3 endpoint
```
When I try to upload an image, I get this error:

```
Zend_Http_Client_Adapter_Exception
Unable to Connect to ssl://z.example.com.s3-eu-west-1.amazonaws.com:443. Error #0:

Zend_Http_Client_Adapter_Exception: Unable to Connect to ssl://z.example.com.s3-eu-west-1.amazonaws.com:443. Error #0:  in /var/www/omeka/application/libraries/Zend/Http/Client/Adapter/Socket.php:235
Stack trace:
#0 /var/www/omeka/application/libraries/Zend/Http/Client.php(1073): Zend_Http_Client_Adapter_Socket->connect('ssl://z.exa...', 443, true)
#1 /var/www/omeka/application/libraries/Omeka/Http/Client.php(36): Zend_Http_Client->request('DELETE')
#2 /var/www/omeka/application/libraries/Zend/Service/Amazon/S3.php(693): Omeka_Http_Client->request('DELETE')
#3 /var/www/omeka/application/libraries/Zend/Service/Amazon/S3.php(553): Zend_Service_Amazon_S3->_makeRequest('DELETE', 'z.exampl...')
#4 /var/www/omeka/application/libraries/Omeka/Storage/Adapter/ZendS3.php(136): Zend_Service_Amazon_S3->removeObject('z.exampl...')
#5 /var/www/omeka/application/libraries/Omeka/Storage.php(67): Omeka_Storage_Adapter_ZendS3->delete('original/f5db19...')
#6 /var/www/omeka/application/models/File.php(329): Omeka_Storage->__call('delete', Array)
#7 /var/www/omeka/application/models/File.php(338): File->unlinkFile()
#8 /var/www/omeka/application/libraries/Omeka/Record/AbstractRecord.php(583): File->_delete()
#9 /var/www/omeka/application/models/Job/FileProcessUpload.php(25): Omeka_Record_AbstractRecord->delete()
#10 /var/www/omeka/application/libraries/Omeka/Job/Dispatcher/Adapter/Synchronous.php(25): Job_FileProcessUpload->perform()
#11 /var/www/omeka/application/libraries/Omeka/Job/Dispatcher/Default.php(137): Omeka_Job_Dispatcher_Adapter_Synchronous->send('{"className":"J...', Array)
#12 /var/www/omeka/application/models/File.php(203): Omeka_Job_Dispatcher_Default->send('Job_FileProcess...', Array)
#13 /var/www/omeka/application/libraries/Omeka/Record/AbstractRecord.php(280): File->afterSave(Array)
#14 /var/www/omeka/application/libraries/Omeka/Record/AbstractRecord.php(548): Omeka_Record_AbstractRecord->runCallbacks('afterSave', Array)
#15 /var/www/omeka/application/models/Item.php(336): Omeka_Record_AbstractRecord->save()
#16 /var/www/omeka/application/models/Item.php(249): Item->saveFiles()
#17 /var/www/omeka/application/libraries/Omeka/Record/AbstractRecord.php(280): Item->afterSave(Array)
#18 /var/www/omeka/application/libraries/Omeka/Record/AbstractRecord.php(548): Omeka_Record_AbstractRecord->runCallbacks('afterSave', Array)
#19 /var/www/omeka/application/libraries/Omeka/Controller/AbstractActionController.php(188): Omeka_Record_AbstractRecord->save(false)
#20 /var/www/omeka/application/controllers/ItemsController.php(148): Omeka_Controller_AbstractActionController->addAction()
#21 /var/www/omeka/application/libraries/Zend/Controller/Action.php(516): ItemsController->addAction()
#22 /var/www/omeka/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('addAction')
#23 /var/www/omeka/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#24 /var/www/omeka/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#25 /var/www/omeka/application/libraries/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#26 /var/www/omeka/application/libraries/Omeka/Application.php(73): Zend_Application->run()
#27 /var/www/omeka/admin/index.php(28): Omeka_Application->run()
#28 {main}
```
Nothing is stored in the S3 bucket. 

Anyone got a clue as to what I am doing wrong?

**Comment by zerocrates** [comment]
I think the `Error #0` refers to an issue with the SSL setup for PHP on your machine.

I believe the issue is that you need to set [a php.ini setting for where SSL certificates are stored on your server](http://php.net/manual/en/openssl.configuration.php). This differs from server to server (or really, distribution to distribution).
